baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Dr Joshua Rhodes'
theme = 'PaperMod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[params.homeInfoParams]
Title = "Josh Rhodes"
Content = "Lecturer in Digital History"
imageUrl = "images/2026-03-28 13.03.20.jpg"
imageTitle = "<title of image as alt>"
imageWidth = 240
imageHeight = 240


name = "Linkedin"
url = "https://www.linkedin.com/in/joshua-rhodes-06021b112/"

[[params.socialIcons]]
name = "Bluesky"
url = "https://bsky.app/profile/joshrhodes.bsky.social"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/josh-rhodes"

[[params.socialIcons]]
name = "Youtube"
url = "https://github.com/josh-rhodes"

[[params.socialIcons]]
name = "Orcid"
url = "https://orcid.org/0000-0002-4017-2777"

[[params.socialIcons]]
name = "UCL Staff Profile"
url = "https://www.ucl.ac.uk/social-historical-sciences/history/people/academic-staff/dr-joshua-rhodes"

[[menu.main]]
identifier = "posts"
name = "About"
url = "/about-me/"
weight = 1

[[menu.main]]
identifier = "About me"
name = "Posts"
url = "/posts/my-first-post/"
weight = 2

[[menu.main]]
identifier = "Data"
name = "Data"
url = "/data/"
weight = 3

[[menu.main]]
identifier = "Code"
name = "Code"
url = "/code/"
weight = 4

[[menu.main]]
identifier = "Publications"
name = "Publications"
url = "/publications/"
weight = 5

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/search/"
weight = 6

[params]
ShowReadingTime = true
label.icon = "/images/Dr Joshua Rhodes.jpg"
ShowWordCount = true
